import Design1 from "@/assets/design1.jpg";
import Design2 from "@/assets/design2.jpg";
import Design3 from "@/assets/design3.webp";
import { TemplateConfig } from "./types";

export const templateRegistry: TemplateConfig[] = [
  // ─── Existing templates ───────────────────────────────────────────────────
  {
    id: "basic",
    name: "Basic Design",
    thumbnail: Design1,
    premium: false,
    layout: "single-column",
    main: [
      { id: "hero", props: {} },
      { id: "aboutMe", props: {} },
      { id: "experience", props: {} },
      {
        id: "education",
        props: { titleOrientation: "flex-row", orientation: "flex-col" },
      },
      {
        id: "certificates",
        props: { titleOrientation: "flex-row", orientation: "flex-col" },
      },
      { id: "languages", props: {} },
      { id: "projects", props: {} },
      { id: "softSkills", props: { orientation: "flex-col" } },
      { id: "skills", props: {} },
    ],
    styles: {
      pageWidth: "sm:w-[800px]",
      font: "font-sans",
      headerBg: "",
      sectionTitleStyle: "",
      defaultAccent: "#1e3a5f",
      spacing: "p-12",
    },
  },
  {
    id: "alt",
    name: "Modern Design",
    thumbnail: Design2,
    premium: false,
    layout: "two-column",
    sidebarWidth: "35%",
    sidebarBg: "bg-blue-950",
    sidebarTextColor: "text-neutral-50",
    sidebar: [
      { id: "contact", props: { title: true, orientation: "flex-col", font: "text-md", textColor: "#fff" } },
      { id: "education", props: { orientation: "flex-col", titleOrientation: "flex-col" } },
      { id: "certificates", props: { orientation: "flex-col", titleOrientation: "flex-col" } },
      { id: "softSkills", props: { orientation: "flex-col", titleOrientation: "flex-col" } },
    ],
    main: [
      { id: "title", props: { orientation: "flex-col" } },
      { id: "aboutMe", props: {} },
      { id: "projects", props: {} },
      { id: "experience", props: {} },
      { id: "languages", props: {} },
      { id: "skills", props: {} },
    ],
    styles: {
      pageWidth: "sm:w-[1000px]",
      font: "font-sans",
      headerBg: "bg-blue-950",
      sectionTitleStyle: "text-2xl font-bold",
      defaultAccent: "#1e3a5f",
      spacing: "p-12",
    },
  },
  {
    id: "basic2",
    name: "Harvard Design",
    thumbnail: Design3,
    premium: false,
    layout: "single-column",
    main: [
      {
        id: "title",
        props: {
          extraStyle: "w-full items-center justify-center poppins-bold tracking-wider",
          extraStyleTitle: "text-4xl",
          orientation: "flex-col",
          extraStyleSubTitle: "text-2xl poppins-light",
        },
      },
      { id: "contact", props: { extraStyle: "justify-center items-center" } },
      {
        id: "aboutMe",
        props: {
          fontSize: "text-sm poppins-light",
          additionClass: "border-b border-black poppins-semibold text-xl",
          margin: "mb-4",
        },
      },
      {
        id: "experience",
        props: {
          fontSize: "text-sm px-4 poppins-light",
          margin: "mb-4",
          additionClass: "border-b border-black poppins-semibold text-xl",
        },
      },
      {
        id: "education",
        props: {
          titleOrientation: "flex-row",
          orientation: "flex-col",
          fontSize: "text-sm px-4 poppins-light",
          margin: "mb-4",
          additionClass: "border-b border-black poppins-semibold text-xl",
        },
      },
      {
        id: "certificates",
        props: {
          titleOrientation: "flex-row",
          orientation: "flex-col",
          fontSize: "text-sm px-4 poppins-light",
          margin: "mb-4",
          additionClass: "border-b border-black poppins-semibold text-xl",
        },
      },
      {
        id: "languages",
        props: {
          fontSize: "text-sm px-4 poppins-light",
          margin: "mb-4",
          additionClass: "border-b border-black poppins-semibold text-xl",
        },
      },
      {
        id: "projects",
        props: {
          fontSize: "text-sm poppins-light",
          margin: "mb-4",
          additionClass: "border-b border-black poppins-semibold text-xl",
        },
      },
      {
        id: "softSkills",
        props: {
          orientation: "flex-col",
          fontSize: "text-sm px-4 poppins-light",
          margin: "mb-4",
          additionClass: "border-b border-black poppins-semibold text-xl",
        },
      },
    ],
    styles: {
      pageWidth: "sm:w-[800px]",
      font: "font-sans",
      headerBg: "",
      sectionTitleStyle: "border-b border-black poppins-semibold text-xl",
      defaultAccent: "#374151",
      spacing: "p-4 tracking-wide",
    },
  },

  // ─── New templates (config-only) ─────────────────────────────────────────
  {
    id: "minimal",
    name: "Minimal",
    thumbnail: Design1,
    premium: false,
    layout: "single-column",
    main: [
      { id: "hero", props: {} },
      { id: "aboutMe", props: { fontSize: "text-sm", margin: "mb-6" } },
      { id: "experience", props: { margin: "mb-6" } },
      { id: "education", props: { orientation: "flex-col", titleOrientation: "flex-row", margin: "mb-6" } },
      { id: "projects", props: { margin: "mb-6" } },
      { id: "skills", props: {} },
      { id: "languages", props: {} },
      { id: "certificates", props: { orientation: "flex-col", titleOrientation: "flex-row" } },
      { id: "softSkills", props: { orientation: "flex-col" } },
    ],
    styles: {
      pageWidth: "sm:w-[800px]",
      font: "font-serif",
      headerBg: "",
      sectionTitleStyle: "text-xl font-light tracking-widest uppercase",
      defaultAccent: "#374151",
      spacing: "p-16",
    },
  },
  {
    id: "creative",
    name: "Creative",
    thumbnail: Design2,
    premium: true,
    layout: "two-column",
    sidebarWidth: "35%",
    sidebarBg: "bg-neutral-900",
    sidebarTextColor: "text-white",
    sidebar: [
      { id: "contact", props: { title: true, orientation: "flex-col", font: "text-sm", textColor: "#fff" } },
      { id: "skills", props: {} },
      { id: "softSkills", props: { orientation: "flex-col", titleOrientation: "flex-col" } },
      { id: "languages", props: { orientation: "flex-col" } },
    ],
    main: [
      { id: "title", props: { orientation: "flex-col" } },
      { id: "aboutMe", props: { margin: "mb-4" } },
      { id: "experience", props: { margin: "mb-4" } },
      { id: "projects", props: { margin: "mb-4" } },
      { id: "education", props: { orientation: "flex-col", titleOrientation: "flex-row" } },
      { id: "certificates", props: { orientation: "flex-col", titleOrientation: "flex-row" } },
    ],
    styles: {
      pageWidth: "sm:w-[1000px]",
      font: "font-sans",
      headerBg: "bg-neutral-900",
      sectionTitleStyle: "text-xl font-bold",
      defaultAccent: "#6d28d9",
      spacing: "p-10",
    },
  },
  {
    id: "executive",
    name: "Executive",
    thumbnail: Design3,
    premium: true,
    layout: "single-column",
    main: [
      { id: "hero", props: {} },
      { id: "aboutMe", props: { additionClass: "uppercase text-sm tracking-widest font-semibold", margin: "mb-6" } },
      { id: "experience", props: { margin: "mb-6", additionClass: "uppercase text-sm tracking-widest font-semibold" } },
      { id: "education", props: { orientation: "flex-col", titleOrientation: "flex-row", margin: "mb-6", additionClass: "uppercase text-sm tracking-widest font-semibold" } },
      { id: "certificates", props: { orientation: "flex-col", titleOrientation: "flex-row", additionClass: "uppercase text-sm tracking-widest font-semibold" } },
      { id: "skills", props: {} },
      { id: "languages", props: {} },
      { id: "projects", props: { margin: "mb-6" } },
      { id: "softSkills", props: { orientation: "flex-col", additionClass: "uppercase text-sm tracking-widest font-semibold" } },
    ],
    styles: {
      pageWidth: "sm:w-[800px]",
      font: "font-serif",
      headerBg: "",
      sectionTitleStyle: "uppercase text-sm tracking-widest font-semibold border-b border-neutral-400",
      defaultAccent: "#374151",
      spacing: "p-12",
    },
  },
  {
    id: "tech",
    name: "Tech",
    thumbnail: Design1,
    premium: true,
    layout: "two-column",
    sidebarWidth: "30%",
    sidebarBg: "bg-gray-900",
    sidebarTextColor: "text-green-400",
    sidebar: [
      { id: "skills", props: {} },
      { id: "contact", props: { title: true, orientation: "flex-col", font: "text-sm", textColor: "#4ade80" } },
      { id: "softSkills", props: { orientation: "flex-col", titleOrientation: "flex-col" } },
      { id: "languages", props: {} },
    ],
    main: [
      { id: "title", props: { orientation: "flex-col" } },
      { id: "aboutMe", props: { fontSize: "text-sm", margin: "mb-4" } },
      { id: "experience", props: { margin: "mb-4" } },
      { id: "projects", props: { margin: "mb-4" } },
      { id: "education", props: { orientation: "flex-col", titleOrientation: "flex-row" } },
      { id: "certificates", props: { orientation: "flex-col", titleOrientation: "flex-row" } },
    ],
    styles: {
      pageWidth: "sm:w-[1000px]",
      font: "font-mono",
      headerBg: "bg-gray-900",
      sectionTitleStyle: "text-lg font-bold font-mono",
      defaultAccent: "#166534",
      spacing: "p-8",
    },
  },
  {
    id: "compact",
    name: "Compact",
    thumbnail: Design3,
    premium: false,
    layout: "single-column",
    main: [
      { id: "hero", props: {} },
      { id: "aboutMe", props: { fontSize: "text-xs", margin: "mb-2" } },
      { id: "experience", props: { fontSize: "text-xs", margin: "mb-2" } },
      { id: "education", props: { orientation: "flex-col", titleOrientation: "flex-row", fontSize: "text-xs", margin: "mb-2" } },
      { id: "skills", props: {} },
      { id: "languages", props: { fontSize: "text-xs" } },
      { id: "certificates", props: { orientation: "flex-col", titleOrientation: "flex-row", fontSize: "text-xs", margin: "mb-2" } },
      { id: "projects", props: { fontSize: "text-xs", margin: "mb-2" } },
      { id: "softSkills", props: { orientation: "flex-col", fontSize: "text-xs", margin: "mb-2" } },
    ],
    styles: {
      pageWidth: "sm:w-[800px]",
      font: "font-sans",
      headerBg: "",
      sectionTitleStyle: "text-sm font-bold",
      defaultAccent: "#475569",
      spacing: "p-6",
    },
  },
];
